db.url=${DB_URL:jdbc:mysql://dsm6:3307/javadb?useSSL=false&serverTimezone=UTC}
db.username=${DB_USERNAME:java_user}
db.password=${DB_PASSWORD:Password1*}
db.driver=com.mysql.cj.jdbc.Driver
db.ddl-auto=${DB_DDL_AUTO:validate}
db.show-sql=${DB_SHOW_SQL:false}
